- name: put /root/k8s-zookeeper-config.yaml
  template: src=k8s-zookeeper-config.yaml dest=/root/k8s-zookeeper-config.yaml

- name: create /data/pvs
  file: dest=/data/pvs state=directory owner=root mode=0600

- name: put a zookeeper-pv1.yaml file
  template: src=pv1.yaml dest=/root/zookeeper-pv1.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ zookeeper_cluster_namespace }} | grep zookeeper-data-1
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ zookeeper_cluster_namespace }} -f /root/zookeeper-pv1.yaml
  when: result|failed

- name: put a zookeeper-pv2.yaml file
  template: src=pv2.yaml dest=/root/zookeeper-pv2.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ zookeeper_cluster_namespace }} | grep zookeeper-data-2
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ zookeeper_cluster_namespace }} -f /root/zookeeper-pv2.yaml
  when: result|failed

- name: put a zookeeper-pv3.yaml file
  template: src=pv3.yaml dest=/root/zookeeper-pv3.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ zookeeper_cluster_namespace }} | grep zookeeper-data-3
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ zookeeper_cluster_namespace }} -f /root/zookeeper-pv3.yaml
  when: result|failed

- name: check if a Helm release for zookeeper-cluster is present
  shell: helm list --namespace={{ zookeeper_cluster_namespace }} | grep zookeeper-cluster-release
  register: result
  ignore_errors: true

- name: enable the incubator repo
  shell: helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/

- name: install a Zookeeper cluster using a Helm chart
  shell: helm install -f /root/k8s-zookeeper-config.yaml incubator/zookeeper --namespace {{ zookeeper_cluster_namespace }} --name zookeeper-cluster-release
  when: result|failed
